package dhcpclient

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/angelfreak/net/pkg/system"
	"github.com/angelfreak/net/pkg/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// fakeBusybox records every call except awk (a pure filter that runs
// concurrently in a pipeline, so logging it would make the order racy) and
// answers `ip -4 route show` with $CURRENT_ROUTES, so the script's lease
// handling can be asserted without touching the host's interfaces.
const fakeBusybox = `#!/bin/sh
[ "$1" = awk ] && { shift; exec awk "$@"; }
echo "$*" >> "$CALLS"
[ "$1 $2 $3 $4" = "ip -4 route show" ] && printf '%s\n' "$CURRENT_ROUTES"
exit 0
`

type scriptRun struct {
	resolvConf string
	dnsOwned   string
	calls      string
}

// runUdhcpcScript runs the generated script for one udhcpc event, the way
// udhcpc does: event as $1, lease details in the environment.
func runUdhcpcScript(t *testing.T, resolvContent string, owned bool, event string, env map[string]string) scriptRun {
	t.Helper()
	dir := t.TempDir()
	bin := filepath.Join(dir, "bin")
	require.NoError(t, os.Mkdir(bin, 0755))
	require.NoError(t, os.WriteFile(filepath.Join(bin, "busybox"), []byte(fakeBusybox), 0755))
	require.NoError(t, os.WriteFile(filepath.Join(bin, "logger"), []byte("#!/bin/sh\nexit 0\n"), 0755))

	run := scriptRun{
		resolvConf: filepath.Join(dir, "resolv.conf"),
		dnsOwned:   filepath.Join(dir, "dns-owned"),
		calls:      filepath.Join(dir, "calls"),
	}
	require.NoError(t, os.WriteFile(run.resolvConf, []byte(resolvContent), 0644))
	if owned {
		require.NoError(t, os.WriteFile(run.dnsOwned, nil, 0644))
	}
	script := filepath.Join(dir, "udhcpc.script")
	require.NoError(t, os.WriteFile(script, []byte(UdhcpcScript(run.resolvConf, run.dnsOwned)), 0700))

	// Exec the file directly, as udhcpc does. Running it via /bin/sh would
	// hide a noexec mount, which once left the interface without an address.
	cmd := exec.Command(script, event)
	cmd.Env = []string{"PATH=" + bin + ":" + os.Getenv("PATH"), "CALLS=" + run.calls}
	for k, v := range env {
		cmd.Env = append(cmd.Env, k+"="+v)
	}
	out, err := cmd.CombinedOutput()
	require.NoError(t, err, "script failed: %s", out)
	return run
}

func (r scriptRun) resolv(t *testing.T) string {
	t.Helper()
	b, err := os.ReadFile(r.resolvConf)
	require.NoError(t, err)
	return string(b)
}

func (r scriptRun) callLines(t *testing.T) []string {
	t.Helper()
	b, err := os.ReadFile(r.calls)
	if os.IsNotExist(err) {
		return nil
	}
	require.NoError(t, err)
	return strings.Split(strings.TrimSpace(string(b)), "\n")
}

var renewEnv = map[string]string{
	"interface": "wlan0",
	"ip":        "192.168.0.105",
	"subnet":    "255.255.255.0",
	"router":    "192.168.0.1",
	"dns":       "217.26.160.4 217.26.160.5",
}

// While net owns DNS (its configured servers, or Tailscale's via
// accept_dns), an hourly lease renewal must not rewrite resolv.conf. The
// immutable lock used to hide this write; accept_dns lifts that lock.
func TestUdhcpcScript_RenewLeavesNetOwnedResolvConfAlone(t *testing.T) {
	const tailscale = "# resolv.conf(5) file generated by tailscale\nnameserver 100.100.100.100\nsearch panga-pirate.ts.net\n"
	run := runUdhcpcScript(t, tailscale, true, "renew", renewEnv)

	assert.Equal(t, tailscale, run.resolv(t))
	assert.Contains(t, run.callLines(t), "ifconfig wlan0 192.168.0.105 netmask 255.255.255.0", "the lease itself must still be applied")
}

// When net does not own DNS (dns: dhcp, or nothing configured), the lease's
// servers go into resolv.conf exactly as udhcpc's stock script writes them.
func TestUdhcpcScript_RenewWritesLeaseDNSWhenNotOwned(t *testing.T) {
	run := runUdhcpcScript(t, "nameserver 9.9.9.9\n", false, "renew", renewEnv)
	assert.Equal(t, "\nnameserver 217.26.160.4\nnameserver 217.26.160.5\n", run.resolv(t))
}

func TestUdhcpcScript_BoundWritesDomain(t *testing.T) {
	env := map[string]string{"interface": "wlan0", "ip": "10.0.0.5", "subnet": "255.255.255.0", "dns": "10.0.0.1", "domain": "lan"}
	run := runUdhcpcScript(t, "", false, "bound", env)
	assert.Equal(t, "domain lan\nnameserver 10.0.0.1\n", run.resolv(t))
}

// The lease is applied like the stock script: default routes on the
// interface are only flushed when the router changed.
func TestUdhcpcScript_RenewReplacesChangedDefaultRoute(t *testing.T) {
	env := map[string]string{"CURRENT_ROUTES": "default via 10.0.0.1 dev wlan0"}
	for k, v := range renewEnv {
		env[k] = v
	}
	run := runUdhcpcScript(t, "", true, "renew", env)

	assert.Equal(t, []string{
		"ifconfig wlan0 192.168.0.105 netmask 255.255.255.0",
		"ip -4 route show dev wlan0",
		"ip -4 route flush exact 0.0.0.0/0 dev wlan0",
		"ip -4 route add default via 192.168.0.1 dev wlan0",
	}, run.callLines(t))
}

func TestUdhcpcScript_RenewKeepsUnchangedDefaultRoute(t *testing.T) {
	env := map[string]string{"CURRENT_ROUTES": "default via 192.168.0.1 dev wlan0"}
	for k, v := range renewEnv {
		env[k] = v
	}
	run := runUdhcpcScript(t, "", true, "renew", env)
	assert.NotContains(t, run.callLines(t), "ip -4 route flush exact 0.0.0.0/0 dev wlan0")
}

func TestUdhcpcScript_DeconfigFlushesInterface(t *testing.T) {
	run := runUdhcpcScript(t, "nameserver 1.1.1.1\n", true, "deconfig", map[string]string{"interface": "wlan0"})
	assert.Equal(t, []string{
		"ip link set wlan0 up",
		"ip -4 addr flush dev wlan0",
		"ip -4 route flush dev wlan0",
	}, run.callLines(t))
	assert.Equal(t, "nameserver 1.1.1.1\n", run.resolv(t))
}

// newScriptTestManager returns a manager whose runtime files and udhcpc
// script live in temp dirs.
func newScriptTestManager(t *testing.T, executor types.SystemExecutor) (*Manager, string) {
	t.Helper()
	tmp := t.TempDir()
	manager := NewManager(executor, &mockLogger{})
	manager.runtimeDir = tmp
	manager.scriptDir = filepath.Join(tmp, "lib")
	return manager, tmp
}

func udhcpcCmd(tmp string) string {
	return "udhcpc -i wlan0 -n -p " + tmp + "/udhcpc.wlan0.pid -R -B -t 6 -T 3 -A 10"
}

// Acquire is the production entry point (wifi/network call it), so it must
// hand udhcpc net's script — written fresh, executable, checking the same
// ownership marker the network manager maintains — after proving it runs.
func TestAcquire_UdhcpcUsesNetScript(t *testing.T) {
	executor := newMockExecutor()
	executor.hasCommands["udhcpc"] = true
	executor.commands["ip addr show wlan0"] = "inet 192.168.1.50/24"
	manager, tmp := newScriptTestManager(t, executor)
	scriptPath := manager.scriptDir + "/udhcpc.script"

	require.NoError(t, manager.Acquire("wlan0", ""))

	executor.assertCommandExecuted(t, udhcpcCmd(tmp)+" -s "+scriptPath)
	probeIdx := slices.Index(executor.executedCmds, scriptPath+" probe")
	udhcpcIdx := slices.Index(executor.executedCmds, udhcpcCmd(tmp)+" -s "+scriptPath)
	require.NotEqual(t, -1, probeIdx, "the script must be executed once before udhcpc relies on it")
	assert.Less(t, probeIdx, udhcpcIdx)
	info, err := os.Stat(scriptPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0700), info.Mode().Perm())
	content, err := os.ReadFile(scriptPath)
	require.NoError(t, err)
	assert.Equal(t, UdhcpcScript("/etc/resolv.conf", types.DNSOwnedPath), string(content))
}

// The script is useless — worse, fatal: no address gets configured — if
// udhcpc cannot exec it (e.g. /run is noexec). Then udhcpc must fall back to
// its stock script: renewals may rewrite resolv.conf, but the lease applies.
func TestAcquire_UdhcpcFallsBackWhenScriptCannotRun(t *testing.T) {
	executor := newMockExecutor()
	executor.hasCommands["udhcpc"] = true
	manager, tmp := newScriptTestManager(t, executor)
	executor.errors[manager.scriptDir+"/udhcpc.script probe"] = errors.New("fork/exec: permission denied")

	require.NoError(t, manager.Acquire("wlan0", ""))
	assert.Contains(t, executor.executedCmds, udhcpcCmd(tmp))
	executor.assertCommandNotExecuted(t, " -s ")
}

func TestAcquire_UdhcpcFallsBackWhenScriptDirUnwritable(t *testing.T) {
	executor := newMockExecutor()
	executor.hasCommands["udhcpc"] = true
	manager, tmp := newScriptTestManager(t, executor)
	blocker := filepath.Join(tmp, "not-a-dir")
	require.NoError(t, os.WriteFile(blocker, nil, 0600))
	manager.scriptDir = filepath.Join(blocker, "lib")

	require.NoError(t, manager.Acquire("wlan0", ""))
	assert.Contains(t, executor.executedCmds, udhcpcCmd(tmp))
}

// udhcpc runs the script as root; a directory others can write to would let
// them swap it, so it is refused.
func TestAcquire_UdhcpcRefusesSharedScriptDir(t *testing.T) {
	executor := newMockExecutor()
	executor.hasCommands["udhcpc"] = true
	manager, tmp := newScriptTestManager(t, executor)
	require.NoError(t, os.MkdirAll(manager.scriptDir, 0755))
	require.NoError(t, os.Chmod(manager.scriptDir, 0777))

	require.NoError(t, manager.Acquire("wlan0", ""))
	assert.Contains(t, executor.executedCmds, udhcpcCmd(tmp))
	executor.assertCommandNotExecuted(t, " -s ")
}

// The probe goes through the real executor, i.e. a direct exec like
// udhcpc's: a script that can be run passes, one the kernel refuses to
// exec (EACCES, as on a noexec mount) fails.
func TestProbeUdhcpcScript_RealExec(t *testing.T) {
	manager, _ := newScriptTestManager(t, system.NewExecutor(&mockLogger{}, false))

	path, err := manager.writeUdhcpcScript()
	require.NoError(t, err)
	assert.NoError(t, manager.probeUdhcpcScript(path))

	require.NoError(t, os.Chmod(path, 0600))
	assert.Error(t, manager.probeUdhcpcScript(path))
}

func TestUdhcpcScript_QuotesPaths(t *testing.T) {
	script := UdhcpcScript("/tmp/it's/resolv.conf", "/run/net/dns-owned")
	assert.Contains(t, script, `RESOLV_CONF='/tmp/it'\''s/resolv.conf'`)
}
